### ISSUE TITLE
no build

### ISSUE THREAD

**Issue by reskwer** [jefrydco/nuxt-pwa-vuetify-firebase-ssr#1]
![image](https://user-images.githubusercontent.com/8849299/38683187-8c9cab06-3e75-11e8-9c99-9ccb8b6f9cc1.png)

**Comment by jefrydco** [comment]
Sorry for late reply, that problem has been fix in https://github.com/jefrydco/nuxt-pwa-vuetify-firebase-ssr/commit/b67e6b204c08da989a10cae6a379e9e511ce39a3
