### ISSUE TITLE
Unbinded Vuetify after build:firebase

### ISSUE THREAD

**Issue by abbrechen** [jefrydco/nuxt-pwa-vuetify-firebase-ssr#2]
First thanks for the environment.

Node: 8.11.3
npm: 6.4.1

Everytime I build for Firebase with `npm run build:firebase` Vuetify components are unknown in dev mode (`npm run dev`).

Example: 

```
[PATH TO PROJECT]\functions\node_modules\vue\dist\vue.runtime.esm.js:574 [Vue warn]: Unknown custom element: <v-app> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Default> at src\layouts\default.vue
       <Root>
```

I tested it on Mac OS Sierra and Windows 10 Pro.
My current solution (but its annoying): I delete the local project and download the latest version from my own gitlab and install the modules. Then its running again. But it does not help to delete the modules folder of the local broken project and install the modules again.

**Comment by jefrydco** [comment]
Hi @abbrechen , sorry for very late reply, has been very busy lately. The idea of `npm run build:firebase` command is when your project is ready to be deployed to Firebase and you want to know how your project looks like if its deployed in Firebase's environment.

After running that command, you have to use `npm run start:firebase` command to see the result. And running `npm run start:firebase` doesn't watch changes. So if you want to change something and see the result immediately, you have to use regular nuxt command, `npm run dev`.

**Comment by jefrydco** [comment]
@abbrechen I've updated the repo, perhaps you would like to check it up again.
